### ISSUE TITLE
Define a clear pipeline

### ISSUE THREAD

**Issue by ymaktepi** [CrumbleZ/dnd-spells#11]
As of now, there is a hard-coded spell that is fetched from dndbeyond (cached into a `html` file if it does not exist). This html file is then parsed and hopefully outputs a `Spell` object.

My take at improving this pipeline is the following:

- Fetch one (or more) spell(s) somewhere
- Save it/them in a clearly defined format
  - Wild guess: good old json, as it is easily readable, parsable, ...
- Execute the current pipeline on the saved files

This has several advantages over the current pipeline:

- Spells can be fetched from anywhere
- Separated scripts can be written to create json files
  - Dnd beyond fetching
  - Other site fetching 
- If a clear json format is specified, it's easy to add spells in an other language
- It is also possible to add custom spells and easily edit them in json (or whatever format)

The format for the current version could simply be a list of spell objects saved in a `json` file.
The attributes of the objects could be the attributes of the python objects.

What should be clearly specified if we plan to have an other language supported:
- Cosmetics data that should not be translated
  - For instance schools of magic used for logos
- Non cosmetics which are to be translated
  - For instance schools of magic that are printed
  - Timings
  - AoE
  - Name
  - Description
  - ...

**Comment by CrumbleZ** [comment]
# Summary of proposition

1. Fetcher/translater pairs on one end (source -> json) ; with one pair per source
2. Generator/compiler on the other end (json -> pdf) ;

This sounds good, but still using only one source (DDB) and one language (python).

## Multiple sources
Should we only fetch official data, we're only going to face redundancy of translated data into our json files. I don't find this worth it. Cross-referencing is good for cases where the data we are fetching is doubtable,

## Multiple languages
I suppose you are talking about the tongue, and not a programming language to create more fetchers/translaters or generators/compilers

If we do support multiple languages other than a dumb throw through gTranslate, that means, we need to classify every redundant data type that appears through spells, but moreover, ensure that the translatations respect the context of a fantasy role playing game, which might not the case of a whole bunch of words I am unable to think of at the moment.

# My take

1 . Fetch and translate to json from a single verified source (presumably ddb).
2. Manually edit every spell that is too long to fit on a card in a more condensed and summarized fashion
3. Generate tex and then pdfs file.

The second step has two advantages : 

1. It allows for spells with a long description to still fit in a comprehensive way on a small reference card ([Teleport](https://www.dndbeyond.com/spells/teleport) for example). 
2. Crowdsourcing spells into other languages allows to benefit from the language nuances from crowdsourcers as well as the respect of the fantasy rpg context, assuming the crowdsourcers are trustworthy.

# End word

Let's discuss our options next time we meet, so it's easier to take a definitive decision.
I'll put the results of our reasoning here.
