### ISSUE TITLE
Add a requirements.txt

### ISSUE THREAD

**Issue by thomasroulin** [CrumbleZ/dnd-spells#2]
You could add a [requirements file](https://pip.readthedocs.io/en/1.1/requirements.html). Because I'd like to be able to run the code.

**Comment by CrumbleZ** [comment]
This code is meant to be run by the elite only.

**Comment by nichuguen** [comment]
Is it okay if I push this a little further and add pipenv?

**Comment by CrumbleZ** [comment]
Sounds a bit like overdoing it, but whatever.

**Comment by thomasroulin** [comment]
> Sounds a bit like overdoing it, but whatever.

@CrumbleZ What do you mean ? `pipenv` is easy to setup, easy to use, it's win-win don't you think ?
